platform :ios, '10.0'

use_frameworks!

target 'RxRestClient-Example' do
  pod 'RxRestClient', :path => '../'
  pod 'RxOptional', '~> 5.0.0'
  pod 'ObjectMapper', '~> 3.5.2'
  pod 'AlamofireNetworkActivityIndicator', '~> 3.1.0'
  pod 'SDWebImage', '~> 4.4.2'

  target 'RxRestClient-Example_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end
