name: RxRestClient

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  MacOS:
    name: macOS
    runs-on: macos-10.15
    env:
      WORKSPACE: Example/RxRestClient.xcworkspace
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer

    steps:
    - uses: actions/checkout@v2
      
    - name: Bundle Install
      run: bundle install
      
    - name: CocoaPods
      run: |
        gem install cocoapods
        pod install --project-directory=Example --repo-update
        
    - name: Build iOS
      run: |
        xcodebuild clean build -workspace $WORKSPACE -scheme $SCHEME -destination "$DESTINATION" | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-ios.json" xcpretty -f `xcpretty-json-formatter`
      env:
          SCHEME: RxRestClient-Example
          DESTINATION: platform=iOS Simulator,name=iPhone 11

  CocoaPods:
    name: CocoaPods
    runs-on: macos-10.15
    strategy:
      matrix:
        platform: ['ios']
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
    steps:
    - uses: actions/checkout@v1
      
    - name: CocoaPods ${{ matrix.platform }}
      run: pod lib lint --skip-tests --allow-warnings --verbose --platforms=${{ matrix.platform }} 
