name: RxRestClient

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  MacOS:
    name: macOS
    runs-on: macos-10.15
    env:
      PROJECT: RxRestClient.xcodeproj
      SCHEME: RxRestClient-Package
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer

    steps:
    - uses: actions/checkout@v2
      
    - name: Bundle Install
      run: bundle install
      
    - name: CocoaPods
      run: |
        gem install cocoapods
        pod install --project-directory=Example --repo-update

    - name: Restore SPM Cache
      uses: actions/cache@v1
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Build and test (SPM)
      run: |
        swift build
        swift test

    - name: Generate Xcodeproj
      run: |
        swift package generate-xcodeproj --enable-code-coverage

    - name: Test iOS
      run: |
        xcodebuild clean build test -project $PROJECT -scheme $SCHEME -destination "$DESTINATION" | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-ios.json" xcpretty -f `xcpretty-json-formatter`
        bash <(curl -s https://codecov.io/bash) -cF ios -J 'STDevRxExt'
      env:
          DESTINATION: platform=iOS Simulator,name=iPhone 11

    - name: Test MacOS
      run: |
        xcodebuild clean build test -project $PROJECT -scheme $SCHEME -destination "$DESTINATION" | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-macos.json" xcpretty -f `xcpretty-json-formatter`
        bash <(curl -s https://codecov.io/bash) -cF macos -J 'STDevRxExt'
      env:
          DESTINATION: platform=OS X

    - name: Test TVOS
      run: |
        xcodebuild clean build test -project $PROJECT -scheme $SCHEME -destination "$DESTINATION" | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-tvos.json" xcpretty -f `xcpretty-json-formatter`
        bash <(curl -s https://codecov.io/bash) -cF tvos -J 'STDevRxExt'
      env:
          DESTINATION: platform=tvOS Simulator,name=Apple TV 4K (at 1080p)

  CocoaPods:
    name: CocoaPods
    runs-on: macos-10.15
    strategy:
      matrix:
        platform: ['ios', 'macos', 'tvos']
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
    steps:
    - uses: actions/checkout@v1
      
    - name: CocoaPods ${{ matrix.platform }}
      run: pod lib lint --skip-tests --allow-warnings --verbose --platforms=${{ matrix.platform }} 
